#!/bin/bash

# The location of the openHAB installation
HAB="./openhab"

cd /opt

HOST=`hostname`
DATE=`date +%Y-%m-%d`
BACKUPFILE=openhab-backup@${HOST}_${DATE}_00.tar.gz

echo "Backing up to file " $BACKUPFILE
tar czf ${BACKUPFILE} ${HAB}

echo "Copying backup to NAS..."
scp ${BACKUPFILE} openhab@nas.nj.hilbush.com:~/${HOST}/${BACKUPFILE}
