#!/bin/bash

# The location of the openHAB installation
HAB="./openhab"

if [ $EUID != 0 ]; then
        echo "Please run this as root!"
        exit 1
fi

cd /opt

HOST=`hostname`
DATE=`date +%Y-%m-%d`
BACKUPDIR=/mnt/tank/backup/openhab
BACKUPFILE=openhab-backup@${HOST}_${DATE}_00.tar.gz
IDFILE=/home/mark/.ssh/id_rsa

echo "Backing up to file " $BACKUPFILE
tar czf ${BACKUPFILE} ${HAB}

echo "Copying backup to NAS..."
scp -i ${IDFILE} ${BACKUPFILE} mark@nas.nj.hilbush.com:${BACKUPDIR}/${HOST}/${BACKUPFILE}
