#!/bin/bash

KARAF_CLIENT="/opt/openhab/runtime/karaf/bin/client"

# read the options
TEMP=`getopt --options h --longoptions help,on,off -n $0 -- "$@"`
eval set -- "$TEMP"

# extract options and their arguments into variables.
while true ; do
    case "$1" in
	-h | --help)
		echo "Usage: $0 [--on] [--off]"
		exit 0 
		;;
	--on)
		${KARAF_CLIENT} "log:set DEBUG org.openhab.binding.zwave" 2>/dev/null
		break 
		;;
	--off)
		${KARAF_CLIENT} "log:set INFO org.openhab.binding.zwave" 2>/dev/null
		break 
		;;
	*)
		echo "Reporting current log level..."
		break 
		;;
    esac
done

${KARAF_CLIENT} "log:get org.openhab.binding.zwave" 2>/dev/null | fgrep "org.openhab.binding.zwave"
