#!/bin/bash

HAB_PARENT_DIR="/opt"

FILE_LIST="updateHAB backupHAB serviceHAB startHAB stopHAB restartHAB \
            versionHAB updateZWAVE \
            debugZWAVE debugGC debugGCAL debugASTRO debugMYSQL debugRRD4J debugSMARTHOME debugSQUEEZE debugWX"

cd ${HAB_PARENT_DIR}

echo "Pulling files from repo"
for f in ${FILE_LIST}
do
	wget -N -q --show-progress https://raw.githubusercontent.com/mhilbush/openhab-tools/master/${f}
	chown mark:mark ${f}
	chmod 755 ${f}
done

echo "Done!"

