#!/bin/bash

OH_PS=`ps ax | grep -e '[j]ava *.*openhab'`

#echo ${OH_PS}

OH_PID=`echo ${OH_PS} | awk '{ print $1 }'`

echo "PID: " ${OH_PID}

echo pidstat -r -p ${OH_PID} 2

pidstat -r -p ${OH_PID} 4

