#!/bin/bash

# The location of the openHAB installation
OH2_DIR="/opt/openhab2"

if [ $EUID != 0 ]; then
        echo "Please run this as root!"
        exit 1
fi

echo "Stopping openHAB service"
systemctl stop openhab2.service
sleep 2

#cp /dev/null ${OH2_DIR}/userdata/logs/openhab.log
#cp /dev/null ${OH2_DIR}/userdata/logs/events.log
#cp /dev/null ${OH2_DIR}/userdata/logs/wrapper.log
#cp /dev/null ${OH2_DIR}/userdata/logs/zwave.log
#cp /dev/null ${OH2_DIR}/userdata/logs/audit.log

#rm -f ${OH2_DIR}/userdata/logs/openhab.log.[1-9]
#rm -f ${OH2_DIR}/userdata/logs/events.log.[1-9]
#rm -f ${OH2_DIR}/userdata/logs/wrapper.log.[1-9]
#rm -f ${OH2_DIR}/userdata/logs/zwave.log.[1-9]
#rm -f ${OH2_DIR}/userdata/logs/audit.log.[1-9]

echo "Starting openHAB service"
systemctl start openhab2.service

