#!/bin/bash

DOWN_DIR=/opt/DOWN
SERVICE_DIR=${DOWN_DIR}/service
KARAF_DIR=/opt/openhab/runtime/karaf

if [ ! -d ${SERVICE_DIR} ]; then
	echo "The directory and files are not there: " ${SERVICE_DIR}
	exit 1
fi

echo "Copying files into openHAB runtime directories..."

if [ ! -d ${KARAF_DIR}/lib/wrapper ]; then
	mkdir --parents ${KARAF_DIR}/lib/wrapper
fi

cp -n ${SERVICE_DIR}/openHAB-wrapper ${KARAF_DIR}/bin/
cp -n ${SERVICE_DIR}/openHAB-service ${KARAF_DIR}/bin/
cp -n ${SERVICE_DIR}/openHAB.service ${KARAF_DIR}/bin/
cp -n ${SERVICE_DIR}/openHAB-wrapper.conf ${KARAF_DIR}/etc/
cp -n ${SERVICE_DIR}/libwrapper.so ${KARAF_DIR}/lib/wrapper/
cp -n ${SERVICE_DIR}/karaf-wrapper.jar ${KARAF_DIR}/lib/wrapper/
cp -n ${SERVICE_DIR}/karaf-wrapper-main.jar ${KARAF_DIR}/lib/wrapper/

echo "Enabling openHAB as a service..."
systemctl enable /opt/openhab/runtime/karaf/bin/openHAB.service

