#!/bin/bash

SEPARATOR="-----------------------"

interval=10
onetime=true
noseparator=false
numthreads=all

if ! options=$(getopt -u -o hi:n:os -l help,interval:,one-time,num-threads:,no-separator -- "$@")
then
    echo "Badly formed options"
    exit 1
fi

set -- $options

while [ $# -gt 0 ]
do
    case $1 in
    -i | --interval)
        interval=$2
        onetime=false
        shift 2
        ;;
    -n | --num-threads)
        numthreads=$2
        shift 2
        ;;
    -o | --one-time)
        onetime=true
        noseparator=true
        shift
        ;;
    -s | --no-separator)
        noseparator=true
        shift
        ;;
    -h | --help)
        echo "Usage: top-threads-cpu [-s] [-o] [-i|--interval n] [-n|--num-threads n] [pattern]"
        exit 0
        ;;
    -- )
        shift; 
        break
        ;;
    (*) break
        ;;
    esac
done

if [ $# != 0 ]; then
    pattern=$1
    separator=${SEPARATOR}
fi

if [ "$numthreads" != "1" ]; then
    separator=${SEPARATOR}
fi

if [ ${noseparator} = true ]; then
    unset separator
fi

while true; do
    if [ -z ${pattern+x} ]; then
        if [ "$numthreads" = "all" ]; then
            /opt/openhab2/runtime/bin/client -p habopen -l 0 -- threads --list | \
                awk -F"│" '{ gsub(/[ \t]+$/, "", $2); print $4 $2 }' | \
                sed -e '/CPU time  Name/d' | \
                sort --numeric-sort --reverse
        else
            /opt/openhab2/runtime/bin/client -p habopen -l 0 -- threads --list | \
                awk -F"│" '{ gsub(/[ \t]+$/, "", $2); print $4 $2 }' | \
                sed -e '/CPU time  Name/d' | \
                sort --numeric-sort --reverse | \
                head --lines ${numthreads} ;
        fi
    else
        /opt/openhab2/runtime/bin/client -p habopen -l 0 -- threads --list | \
            awk -F"│" '{ gsub(/[ \t]+$/, "", $2); print $4 $2 }' | \
            grep --line-buffered ${pattern}
    fi
    
    if [ ${onetime} = true ]; then
        break
    fi

    if [ ! -z ${separator+x} ]; then
        echo $separator
    fi
    sleep ${interval}
done

