#!/bin/bash

SEPARATOR="-----------------------"

interval=10
onetime=false
noseparator=false
numthreads=10

if ! options=$(getopt -u -o hi:n:os -l help,interval:,one-time,num-threads:,no-separator -- "$@")
then
    echo "Badly formed options"
    exit 1
fi

set -- $options

echo "Num args: $#"

while [ $# -gt 0 ]
do
    case $1 in
    -i | --interval)
        echo "interval: $2"
        interval=$2
        shift 2
        ;;
    -n | --num-threads)
        echo "numthreads: $2"
        numthreads=$2
        shift 2
        ;;
    -o | --one-time)
        echo "onetime: true"
        onetime=true
        shift
        ;;
    -s | --no-separator)
        echo "No separator"
        noseparator=true
        shift
        ;;
    -h | --help)
        echo "Usage: top-threads-cpu [-o] [-i interval] [nthreads | all | pattern]"
        exit 0
        ;;
    -- )
        shift; 
        break
        ;;
    (*) break
        ;;
    esac
done

if [ $# != 0 ]; then
    pattern=$1
    echo "pattern: $pattern"
    separator=${SEPARATOR}
fi

if [ "$numthreads" != "1" ]; then
    separator=${SEPARATOR}
fi

if [ ${noseparator} = true ]; then
    unset separator
fi

while true; do
    if [ -z ${pattern+x} ]; then
        /opt/openhab2/runtime/bin/client -p habopen -l 0 -- threads --list | \
            awk -F"│" '{ gsub(/[ \t]+$/, "", $2); print $4 $2 }' | \
            sort --numeric-sort --reverse | \
            head --lines ${numthreads} ;
    else
        /opt/openhab2/runtime/bin/client -p habopen -l 0 -- threads --list | \
            awk -F"│" '{ gsub(/[ \t]+$/, "", $2); print $4 $2 }' | \
            grep --line-buffered ${pattern}
    fi
    
    if [ ${onetime} = true ]; then
        break
    fi

    if [ ! -z ${separator+x} ]; then
        echo $separator
    fi
    sleep ${interval}
done

