#!/bin/bash

SEPARATOR="-----------------------"

interval=10
onetime=false

if ! options=$(getopt -u -o hi:o -l help,interval:,one-time -- "$@")
then
    echo "Badly formed options"
    exit 1
fi

set -- $options

while [ $# -gt 0 ]
do
    case $1 in
    -i | --interval)
        interval=$2
        shift; shift
        ;;
    -o | --one-time)
        onetime=true
        shift
        ;;
    -h | --help)
        echo "Usage: top-threads-cpu [-o] [-i interval] [nthreads | all | pattern]"
        exit 0
        ;;
    -- )
        shift; 
        break
        ;;
    (*) break
        ;;
    esac
    shift
done

if [ $# -eq 0 ] ; then
    numthreads="10"
elif [ $1 = "all" ]; then
    numthreads="1000"
elif [[ "$1" =~ ^[0-9]+$ ]]; then
    numthreads=$1
else
    pattern=$1
    separator=${SEPARATOR}
fi

if [ "$numthreads" != "1" ]; then
    separator=${SEPARATOR}
fi

while true; do
    if [ -z ${pattern+x} ]; then
        /opt/openhab2/runtime/bin/client -p habopen -l 0 -- threads --list | \
            awk -F"│" '{ gsub(/[ \t]+$/, "", $2); print $4 $2 }' | \
            sort --numeric-sort --reverse | \
            head --lines ${numthreads} ;
    else
        /opt/openhab2/runtime/bin/client -p habopen -l 0 -- threads --list | \
            awk -F"│" '{ gsub(/[ \t]+$/, "", $2); print $4 $2 }' | \
            grep --line-buffered ${pattern}
    fi
    
    if [ ${onetime} = true ]; then
        break
    fi

    if [ ! -z ${separator+x} ]; then
        echo $separator
    fi
    sleep ${interval}
done

