#!/bin/bash

KARAF_DIR="/opt/openhab/runtime"

BINDING="org.openhab.binding.zwave"
COMMANDS="list -s ${BINDING}; \
	log:set DEBUG ${BINDING}; \
	bundle:update ${BINDING}; \
	list -s ${BINDING}; \
	log:get ${BINDING}"

KARAF_DIR="/opt/openhab/runtime/karaf"

${KARAF_DIR}/bin/client -l 0 -- ${COMMANDS}
