#!/bin/bash

BUNDLES="list -s \
	org.openhab.binding.zwave \
	org.openhab.binding.squeezebox \
	org.openhab.binding.globalcache \
	org.openhab.binding.bigassfan \
	org.openhab.binding.sunsetwx \
	org.openhab.binding.systeminfo \
	org.openhab.binding.weatherunderground \
	org.eclipse.smarthome.core \
        org.openhab.core.karaf \
        org.apache.karaf.event"

KARAF_DIR="/opt/openhab2/runtime"

${KARAF_DIR}/bin/client -p habopen -l 0 -- ${BUNDLES}

