#!/bin/bash

BUNDLES="list -s \
	org.apache.karaf.shell.core \
	org.apache.karaf.wrapper.core \
	org.eclipse.smarthome.core \
	org.openhab.binding.astro \
	org.openhab.binding.globalcache \
	org.openhab.binding.http \
	org.eclipse.smarthome.binding.ntp \
	org.openhab.binding.squeezebox \
	org.openhab.binding.sunsetwx \
	org.openhab.binding.systeminfo \
	org.openhab.binding.weather \
	org.openhab.binding.zwave \
	org.openhab.persistence.mysql \
	org.openhab.persistence.rrd4j \
	org.openhab.action.mail"

KARAF_DIR="/opt/openhab/runtime"

${KARAF_DIR}/bin/client -l 0 -- ${BUNDLES}

